import typing as t

from skoll.result import Result
from skoll.config import SMTPConfig

from .primitives import ID
from .objects import Entity, IPInfo
from .typing import Criteria, ListPage, KVBucket
from .messaging import Message, RawMessage, Service


__all__ = ["DB", "Repository", "Mediator", "EmailSender", "IPInfoProvider", "KVStore"]


class IPInfoProvider(t.Protocol):

    async def __call__(self, ip: str) -> IPInfo | None: ...


class DB[T = t.Any](t.Protocol):

    async def close(self) -> None: ...
    async def connect(self) -> None: ...
    def session(self) -> t.AsyncContextManager[T]: ...
    def transaction(self) -> t.AsyncContextManager[T]: ...


class Repository[T: Entity](t.Protocol):

    async def save(self, state: T) -> None: ...
    async def delete(self, criteria: Criteria) -> None: ...
    async def exist(self, criteria: Criteria) -> bool: ...
    async def get(self, criteria: Criteria) -> T | None: ...
    async def list(self, criteria: Criteria) -> ListPage[T]: ...


class KVStore(t.Protocol):

    async def delete(self, key: str) -> None: ...
    async def get(self, key: str) -> str | None: ...
    async def add(self, key: str, value: str, ttl: int | None = None) -> None: ...
    async def update(self, key: str, value: str, ttl: int | None = None) -> None: ...


class Mediator(t.Protocol):

    @property
    def kv(self) -> KVStore: ...
    async def disconnect(self) -> None: ...
    async def unsubscribe(self, id: ID) -> None: ...

    async def subscribe(self, service: Service) -> ID: ...
    async def publish(self, *msg: Message | RawMessage) -> None: ...
    async def request(self, msg: Message | RawMessage) -> Result[t.Any]: ...
    async def connect(self, kv_buckets: list[KVBucket] | None = None) -> None: ...


class EmailSender(t.Protocol):

    async def __call__(self, to: str, title: str, html_body: str, config: SMTPConfig = SMTPConfig.DEFAULT) -> None: ...
